From Stdlib Require Extraction.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFCertificate.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFExtractionDecision.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFExtractionSoundness.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFExtractionTypes.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFFinalCertificateChecker.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFGeneratedPrefixChecker.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFTransportWitnessChecker.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFTransportCoverageChecker.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFWindowTransportChecker.

Extraction Language Haskell.

Extraction "extracted/haskell/PeriodicEDFSchedulability.hs"
  ExtractedPeriodicTask
  EDFPrefixCert
  EDFTransportClass
  EDFTransportCert
  EDFDBFCert
  EDFInfiniteCert
  EDFWindowTransportPairCert
  EDFWindowTransportTargetCert
  PeriodicEDFCheckedSidecarCert
  extracted_periodic_offsets
  extracted_offset_periodic_jobs
  extracted_offset_periodic_codec
  edf_schedulability_decide
  edf_schedulability_counterexample
  check_prefix_slots_match_generated_edf_fast
  transport_class_rep_relevant_jobs
  transport_classes_rep_relevant_jobs
  check_transport_classes_rep_backlog_generated
  periodic_transport_residue_jobs
  check_periodic_transport_residue_coverage
  check_transport_residue_shifts
  check_transport_basis_nodup
  check_transport_classes_rep_periodic_generated
  check_periodic_hyperperiod_state_reset
  check_transport_period_is_hyperperiod
  check_prefix_horizon_covers_hyperperiod
  post_reset_window_horizon
  check_prefix_horizon_covers_post_reset_window
  check_window_transport_targets_complete
  check_window_transport_targets_complete_with_pairs
  window_target_relevant_earlier_jobs
  check_window_target_periodic
  check_window_target_rep_earlier_membership
  check_window_generated_pair_semantics
  check_window_generated_pair_semantics_all
  check_generated_window_pair_target_completed
  check_window_generated_pair_completion
  check_window_generated_pair_completion_all
  post_reset_window_targets_of_certs
  post_reset_window_target_jobs
  check_post_reset_target_list_complete
  check_post_reset_window_target_basis_coverage
  check_post_reset_window_targets_complete_with_pairs
  check_hyperperiod_delta_multiple
  check_hyperperiod_shifted_service_pair
  check_hyperperiod_block_source_pair
  check_hyperperiod_block_source_pair_in_cert
  check_hyperperiod_block_source_pair_in_certs
  check_window_target_pair_coverage
  check_periodic_edf_checked_sidecar_extracted_with_offsets
  check_periodic_edf_checked_sidecar_extracted.
