From Stdlib Require Import Arith Arith.PeanoNat Lia Bool.
From SchedulingTheory Require Import Foundation.Base.

(* ===== Periodic Task Generation Model ===== *)

(* Expected release time of the k-th job of task τ.
   release(k) = offset(τ) + k * period(τ) *)
Definition expected_release (tasks : TaskId -> Task)
    (offset : TaskId -> Time) (τ : TaskId) (k : nat) : Time :=
  offset τ + k * task_period (tasks τ).

(* Expected absolute deadline of the k-th job of task τ.
   deadline(k) = release(k) + relative_deadline(τ) *)
Definition expected_abs_deadline (tasks : TaskId -> Task)
    (offset : TaskId -> Time) (τ : TaskId) (k : nat) : Time :=
  expected_release tasks offset τ k + task_relative_deadline (tasks τ).

(* A job j is generated by the periodic task model if:
   - its release time equals the expected release for its task and index
   - its absolute deadline equals the expected deadline
   - its execution cost is bounded by the task WCET *)
Definition generated_by_periodic_task
    (tasks : TaskId -> Task)
    (offset : TaskId -> Time)
    (jobs : JobId -> Job)
    (j : JobId) : Prop :=
  let τ := job_task (jobs j) in
  let k := job_index (jobs j) in
  job_release (jobs j) = expected_release tasks offset τ k /\
  job_abs_deadline (jobs j) = expected_abs_deadline tasks offset τ k /\
  job_cost (jobs j) <= task_cost (tasks τ).

Definition generated_by_periodic_task_b
    (tasks : TaskId -> Task)
    (offset : TaskId -> Time)
    (jobs : JobId -> Job)
    (j : JobId) : bool :=
  Nat.eqb
    (job_release (jobs j))
    (expected_release tasks offset (job_task (jobs j)) (job_index (jobs j)))
  &&
  Nat.eqb
    (job_abs_deadline (jobs j))
    (expected_abs_deadline tasks offset (job_task (jobs j)) (job_index (jobs j)))
  &&
  Nat.leb
    (job_cost (jobs j))
    (task_cost (tasks (job_task (jobs j)))).

(* All jobs satisfy the periodic generation rule (total-function version). *)
Definition periodic_job_model
    (tasks : TaskId -> Task)
    (offset : TaskId -> Time)
    (jobs : JobId -> Job) : Prop :=
  forall j, generated_by_periodic_task tasks offset jobs j.

(* Restrict the periodic generation requirement to a designated job set J.
   Pairs naturally with feasible_on / feasible_schedule_on. *)
Definition periodic_job_model_on
    (J : JobId -> Prop)
    (tasks : TaskId -> Task)
    (offset : TaskId -> Time)
    (jobs : JobId -> Job) : Prop :=
  forall j, J j -> generated_by_periodic_task tasks offset jobs j.

(* Implicit-deadline task model: relative deadline equals period.
   Required for classic EDF/RM optimality results. *)
Definition implicit_deadline_tasks (tasks : TaskId -> Task) : Prop :=
  forall τ, task_relative_deadline (tasks τ) = task_period (tasks τ).

(* ===== Basic Lemmas ===== *)

(* The release time of a periodically generated job equals expected_release. *)
Lemma generated_job_release :
  forall tasks offset jobs j,
    generated_by_periodic_task tasks offset jobs j ->
    job_release (jobs j) =
      expected_release tasks offset (job_task (jobs j)) (job_index (jobs j)).
Proof.
  intros tasks offset jobs j Hgen.
  exact (proj1 Hgen).
Qed.

(* The absolute deadline of a periodically generated job equals
   release + relative deadline. *)
Lemma generated_job_deadline :
  forall tasks offset jobs j,
    generated_by_periodic_task tasks offset jobs j ->
    job_abs_deadline (jobs j) =
      job_release (jobs j) + task_relative_deadline (tasks (job_task (jobs j))).
Proof.
  intros tasks offset jobs j Hgen.
  destruct Hgen as [Hrel [Hdl _]].
  unfold expected_abs_deadline in Hdl.
  rewrite <- Hrel in Hdl.
  exact Hdl.
Qed.

(* The cost of a periodically generated job is bounded by the task WCET. *)
Lemma generated_job_cost_bounded :
  forall tasks offset jobs j,
    generated_by_periodic_task tasks offset jobs j ->
    job_cost (jobs j) <= task_cost (tasks (job_task (jobs j))).
Proof.
  intros tasks offset jobs j Hgen.
  exact (proj2 (proj2 Hgen)).
Qed.

Lemma generated_by_periodic_task_b_spec :
  forall tasks offset jobs j,
    generated_by_periodic_task_b tasks offset jobs j = true <->
    generated_by_periodic_task tasks offset jobs j.
Proof.
  intros tasks offset jobs j.
  unfold generated_by_periodic_task_b, generated_by_periodic_task.
  rewrite !andb_true_iff.
  rewrite !Nat.eqb_eq.
  rewrite Nat.leb_le.
  tauto.
Qed.

Lemma expected_release_monotone :
  forall tasks offset τ k1 k2,
    k1 <= k2 ->
    expected_release tasks offset τ k1 <=
    expected_release tasks offset τ k2.
Proof.
  intros tasks offset τ k1 k2 Hle.
  unfold expected_release.
  apply Nat.add_le_mono_l.
  pose proof (task_period (tasks τ)) as p.
  apply Nat.mul_le_mono_nonneg_r.
  - lia.
  - exact Hle.
Qed.

Lemma expected_release_step :
  forall tasks offset τ k,
    expected_release tasks offset τ (S k) =
    expected_release tasks offset τ k + task_period (tasks τ).
Proof.
  intros tasks offset τ k.
  unfold expected_release.
  lia.
Qed.

Lemma expected_abs_deadline_step :
  forall tasks offset τ k,
    expected_abs_deadline tasks offset τ (S k) =
    expected_release tasks offset τ k
    + task_period (tasks τ)
    + task_relative_deadline (tasks τ).
Proof.
  intros tasks offset τ k.
  unfold expected_abs_deadline.
  rewrite expected_release_step.
  lia.
Qed.

Lemma generated_job_deadline_implicit :
  forall tasks offset jobs j,
    implicit_deadline_tasks tasks ->
    generated_by_periodic_task tasks offset jobs j ->
    job_abs_deadline (jobs j) =
    expected_release tasks offset (job_task (jobs j)) (S (job_index (jobs j))).
Proof.
  intros tasks offset jobs j Himplicit Hgen.
  destruct Hgen as [Hrel [Hdl Hcost]].
  unfold expected_abs_deadline in Hdl.
  rewrite Himplicit in Hdl.
  rewrite expected_release_step.
  exact Hdl.
Qed.

(* A periodically generated job satisfies the local consistency predicate
   valid_job_of_task defined in Base.v. *)
Lemma generated_implies_valid_job_of_task :
  forall tasks offset jobs j,
    generated_by_periodic_task tasks offset jobs j ->
    valid_job_of_task tasks jobs j.
Proof.
  intros tasks offset jobs j Hgen.
  unfold valid_job_of_task.
  split.
  - exact (generated_job_deadline tasks offset jobs j Hgen).
  - exact (generated_job_cost_bounded tasks offset jobs j Hgen).
Qed.
