From Stdlib Require Extraction.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFCertificate.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFExtractionDecision.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFExtractionTypes.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFFinalCertificateChecker.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFGeneratedPrefixChecker.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFTransportWitnessChecker.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFTransportCoverageChecker.
From RocqSched Require Import TaskModels.Periodic.PeriodicEDFWindowTransportChecker.

Extraction Language Haskell.

Extraction "extracted/haskell/PeriodicEDFSchedulability.hs"
  ExtractedPeriodicTask
  EDFPrefixCert
  EDFTransportClass
  EDFTransportCert
  EDFDBFCert
  EDFInfiniteCert
  EDFWindowTransportPairCert
  EDFWindowTransportTargetCert
  PeriodicEDFCheckedSidecarCert
  edf_schedulability_decide
  edf_schedulability_counterexample
  check_prefix_slots_match_generated_edf
  check_prefix_slots_match_generated_edf_fast
  transport_class_rep_relevant_jobs
  transport_classes_rep_relevant_jobs
  check_transport_classes_rep_backlog_generated
  periodic_transport_residue_jobs
  check_periodic_transport_residue_coverage
  check_transport_residue_shifts
  check_transport_basis_nodup
  check_transport_classes_rep_periodic_generated
  check_periodic_hyperperiod_state_reset
  check_window_transport_targets_complete
  check_window_transport_targets_complete_with_pairs
  window_target_relevant_earlier_jobs
  check_window_target_periodic
  check_window_target_rep_earlier_membership
  check_window_generated_pair_semantics
  check_window_generated_pair_semantics_all
  check_generated_window_pair_target_completed
  check_window_generated_pair_completion
  check_window_generated_pair_completion_all
  check_window_target_pair_coverage
  check_periodic_edf_checked_sidecar_extracted.
