From Stdlib Require Import Arith Arith.PeanoNat Lia List.
From RocqSched Require Import Foundation.Base.
From RocqSched Require Import TaskModels.Periodic.PeriodicTasks.
From RocqSched Require Import TaskModels.Periodic.PeriodicFiniteHorizon.
From RocqSched Require Import Analysis.Common.WorkloadAggregation.
From RocqSched Require Import Analysis.Uniprocessor.DemandBound.

Import ListNotations.

(* ===== Deadline-Bounded Finite Horizon for Periodic Tasks ===== *)

(* The deadline-bounded jobset up to horizon H:
   jobs whose absolute deadline falls within [0, H].
   This is the DBF counterpart to periodic_jobset_upto (which uses release < H).

   Note: we do NOT use a release-time bound here.  A job j belongs to this
   set if its task is in scope, it was generated by the periodic model,
   and its absolute deadline is at most H. *)
Definition periodic_jobset_deadline_upto
    (T : TaskId -> Prop)
    (tasks : TaskId -> Task)
    (offset : TaskId -> Time)
    (jobs : JobId -> Job)
    (H : Time) : JobId -> Prop :=
  fun j =>
    T (job_task (jobs j)) /\
    generated_by_periodic_task tasks offset jobs j /\
    job_abs_deadline (jobs j) <= H.

(* ===== Basic extraction lemmas ===== *)

Lemma periodic_jobset_deadline_upto_implies_task_in_scope :
  forall T tasks offset jobs H j,
    periodic_jobset_deadline_upto T tasks offset jobs H j ->
    T (job_task (jobs j)).
Proof.
  intros T tasks offset jobs H j [HT _]. exact HT.
Qed.

Lemma periodic_jobset_deadline_upto_implies_generated :
  forall T tasks offset jobs H j,
    periodic_jobset_deadline_upto T tasks offset jobs H j ->
    generated_by_periodic_task tasks offset jobs j.
Proof.
  intros T tasks offset jobs H j [_ [Hgen _]]. exact Hgen.
Qed.

Lemma periodic_jobset_deadline_upto_implies_deadline_le :
  forall T tasks offset jobs H j,
    periodic_jobset_deadline_upto T tasks offset jobs H j ->
    job_abs_deadline (jobs j) <= H.
Proof.
  intros T tasks offset jobs H j [_ [_ Hdl]]. exact Hdl.
Qed.

Lemma periodic_jobset_deadline_upto_implies_valid :
  forall T tasks offset jobs H j,
    periodic_jobset_deadline_upto T tasks offset jobs H j ->
    valid_job_of_task tasks jobs j.
Proof.
  intros T tasks offset jobs H j Hjobset.
  exact (generated_implies_valid_job_of_task tasks offset jobs j
    (periodic_jobset_deadline_upto_implies_generated T tasks offset jobs H j Hjobset)).
Qed.

(* ===== Index bound via deadline ===== *)

(* For a periodically generated job with abs_deadline ≤ H:
     abs_deadline = offset + k * p + d ≤ H
   Hence k * p ≤ H - d (since offset ≥ 0 in Nat arithmetic).
   Therefore k < S((H - d) / p) = the DBF count. *)
Lemma periodic_jobset_deadline_upto_implies_index_lt_dbf_count :
  forall T tasks offset jobs H j,
    well_formed_periodic_tasks_on T tasks ->
    0 < task_relative_deadline (tasks (job_task (jobs j))) ->
    periodic_jobset_deadline_upto T tasks offset jobs H j ->
    job_index (jobs j) <
    S ((H - task_relative_deadline (tasks (job_task (jobs j))))
       / task_period (tasks (job_task (jobs j)))).
Proof.
  intros T tasks offset jobs H j Hwf Hd Hjobset.
  pose proof (periodic_jobset_deadline_upto_implies_task_in_scope
                T tasks offset jobs H j Hjobset) as HT.
  pose proof (Hwf _ HT) as Hp.
  pose proof (periodic_jobset_deadline_upto_implies_generated
                T tasks offset jobs H j Hjobset) as Hgen.
  pose proof (periodic_jobset_deadline_upto_implies_deadline_le
                T tasks offset jobs H j Hjobset) as Hdl_le.
  pose proof (generated_job_release tasks offset jobs j Hgen) as Hrel_eq.
  unfold expected_release in Hrel_eq.
  pose proof (generated_job_deadline tasks offset jobs j Hgen) as Hdl_eq.
  (* Hrel_eq : job_release (jobs j) = offset τ + job_index j * period *)
  (* Hdl_eq  : job_abs_deadline (jobs j) = job_release j + rel_dl    *)
  (* Hdl_le  : job_abs_deadline (jobs j) ≤ H                         *)
  (* → job_index j * period ≤ job_release j ≤ H - rel_dl             *)
  apply Nat.lt_succ_r.
  apply (Nat.div_le_lower_bound
           (H - task_relative_deadline (tasks (job_task (jobs j))))
           (task_period (tasks (job_task (jobs j))))
           (job_index (jobs j))).
  + lia.
  + rewrite Nat.mul_comm.
    apply Nat.le_add_le_sub_r.
    apply Nat.le_trans
      with (m := job_release (jobs j) +
                 task_relative_deadline (tasks (job_task (jobs j)))).
    * rewrite Hrel_eq. lia.
    * rewrite <- Hdl_eq. exact Hdl_le.
Qed.

(* ===== Count bound ===== *)

Lemma periodic_jobs_of_task_deadline_upto_count_sound :
  forall T tasks offset jobs H τ l,
    well_formed_periodic_tasks_on T tasks ->
    0 < task_relative_deadline (tasks τ) ->
    NoDup (map (fun j => job_index (jobs j)) l) ->
    (forall j,
      In j l ->
      periodic_jobset_deadline_upto T tasks offset jobs H j /\
      job_task (jobs j) = τ) ->
    length l <= S ((H - task_relative_deadline (tasks τ))
                   / task_period (tasks τ)).
Proof.
  intros T tasks offset jobs H τ l Hwf Hd Hnodup_idx Hjobs.
  set (cnt := S ((H - task_relative_deadline (tasks τ))
                 / task_period (tasks τ))).
  pose (idx := fun j => job_index (jobs j)).
  assert (Hincl : incl (map idx l) (seq 0 cnt)).
  {
    intros k Hk.
    apply in_map_iff in Hk.
    destruct Hk as [j [Hidx Hj]].
    subst k.
    rewrite in_seq.
    split.
    - apply Nat.le_0_l.
    - destruct (Hjobs j Hj) as [Hjobset Htask].
      pose proof (periodic_jobset_deadline_upto_implies_index_lt_dbf_count
                    T tasks offset jobs H j Hwf) as Hlt.
      rewrite Htask in Hlt.
      apply Hlt.
      + exact Hd.
      + exact Hjobset.
  }
  eapply Nat.le_trans.
  - replace (length l) with (length (map idx l)) by apply List.length_map.
    apply NoDup_incl_length with (l := map idx l) (l' := seq 0 cnt);
      try exact Hnodup_idx.
    exact Hincl.
  - rewrite length_seq. lia.
Qed.

(* ===== Demand bound ===== *)

(* The total demand of periodic jobs with absolute deadline ≤ H is bounded by
   the periodic DBF.  This is the central bridge from job-level demand to the
   abstract analysis function. *)
Lemma periodic_demand_le_dbf :
  forall T tasks offset jobs H τ l,
    well_formed_periodic_tasks_on T tasks ->
    0 < task_relative_deadline (tasks τ) ->
    NoDup (map (fun j => job_index (jobs j)) l) ->
    (forall j,
      In j l ->
      periodic_jobset_deadline_upto T tasks offset jobs H j /\
      job_task (jobs j) = τ) ->
    total_job_cost jobs l <= periodic_dbf tasks τ H.
Proof.
  intros T tasks offset jobs H τ l Hwf Hd Hnodup_idx Hjobs.
  unfold periodic_dbf.
  destruct (Nat.ltb_spec H (task_relative_deadline (tasks τ))) as [Hlt | Hge].
  - (* H < d: DBF = 0, so l must be empty *)
    (* Every job in l has deadline ≤ H < d.
       But deadline = offset + k*p + d ≥ d > H.  Contradiction → l = []. *)
    assert (Hl : l = []).
    {
      destruct l as [| j l']; [reflexivity |].
      exfalso.
      destruct (Hjobs j (in_eq j l')) as [Hjobset Htask].
      pose proof (periodic_jobset_deadline_upto_implies_generated
                    T tasks offset jobs H j Hjobset) as Hgen.
      pose proof (periodic_jobset_deadline_upto_implies_deadline_le
                    T tasks offset jobs H j Hjobset) as Hdl_le.
      pose proof (generated_job_deadline tasks offset jobs j Hgen) as Hdl_eq.
      rewrite Htask in Hdl_eq.
      lia.
    }
    subst l. simpl. lia.
  - (* H ≥ d: use count bound *)
    eapply Nat.le_trans.
    + eapply (total_job_cost_le_length_mul jobs l (task_cost (tasks τ))).
      intros j Hj.
      destruct (Hjobs j Hj) as [Hjobset Htask].
      rewrite <- Htask.
      exact (generated_job_cost_bounded tasks offset jobs j
               (periodic_jobset_deadline_upto_implies_generated
                  T tasks offset jobs H j Hjobset)).
    + pose proof (periodic_jobs_of_task_deadline_upto_count_sound
                    T tasks offset jobs H τ l Hwf Hd Hnodup_idx Hjobs) as Hcount.
      apply Nat.mul_le_mono_r.
      exact Hcount.
Qed.
