From Stdlib Require Import Arith Arith.PeanoNat Lia List.
From RocqSched Require Import Foundation.Base.
From RocqSched Require Import TaskModels.Periodic.PeriodicTasks.
From RocqSched Require Import TaskModels.Sporadic.SporadicTasks.
From RocqSched Require Import TaskModels.Sporadic.SporadicFiniteHorizon.
From RocqSched Require Import TaskModels.Sporadic.SporadicWorkload.
From RocqSched Require Import Analysis.Common.WorkloadAggregation.
From RocqSched Require Import Analysis.Uniprocessor.DemandBound.

Import ListNotations.

(* ===== Deadline-Bounded Finite Horizon for Sporadic Tasks ===== *)

(* The deadline-bounded jobset for sporadic tasks:
   jobs whose task is in scope, generated by the sporadic model,
   and whose absolute deadline is at most H.

   Key difference from sporadic_jobset_upto (which uses release < H):
   here we bound by deadline ≤ H.  Since sporadic deadlines satisfy
     abs_deadline = release + rel_deadline ≥ k * period + rel_deadline,
   this gives a DBF-style count. *)
Definition sporadic_jobset_deadline_upto
    (T : TaskId -> Prop)
    (tasks : TaskId -> Task)
    (jobs : JobId -> Job)
    (H : Time) : JobId -> Prop :=
  fun j =>
    T (job_task (jobs j)) /\
    generated_by_sporadic_task tasks jobs j /\
    job_abs_deadline (jobs j) <= H.

(* ===== Basic extraction lemmas ===== *)

Lemma sporadic_jobset_deadline_upto_implies_task_in_scope :
  forall T tasks jobs H j,
    sporadic_jobset_deadline_upto T tasks jobs H j ->
    T (job_task (jobs j)).
Proof.
  intros T tasks jobs H j [HT _]. exact HT.
Qed.

Lemma sporadic_jobset_deadline_upto_implies_generated :
  forall T tasks jobs H j,
    sporadic_jobset_deadline_upto T tasks jobs H j ->
    generated_by_sporadic_task tasks jobs j.
Proof.
  intros T tasks jobs H j [_ [Hgen _]]. exact Hgen.
Qed.

Lemma sporadic_jobset_deadline_upto_implies_deadline_le :
  forall T tasks jobs H j,
    sporadic_jobset_deadline_upto T tasks jobs H j ->
    job_abs_deadline (jobs j) <= H.
Proof.
  intros T tasks jobs H j [_ [_ Hdl]]. exact Hdl.
Qed.

Lemma sporadic_jobset_deadline_upto_implies_valid :
  forall T tasks jobs H j,
    sporadic_jobset_deadline_upto T tasks jobs H j ->
    valid_job_of_task tasks jobs j.
Proof.
  intros T tasks jobs H j Hjobset.
  exact (generated_sporadic_implies_valid_job_of_task tasks jobs j
    (sporadic_jobset_deadline_upto_implies_generated T tasks jobs H j Hjobset)).
Qed.

(* ===== Index bound via deadline ===== *)

(* For a sporadic job with abs_deadline ≤ H:
   - abs_deadline = release + rel_deadline  (from valid_job_of_task)
   - release ≥ k * period               (from generated_by_sporadic_task)
   Therefore: k * period + rel_deadline ≤ H,
   giving k < S((H - rel_deadline) / period) = the DBF count. *)
Lemma sporadic_jobset_deadline_upto_implies_index_lt_dbf_count :
  forall T tasks jobs H j,
    well_formed_periodic_tasks_on T tasks ->
    0 < task_relative_deadline (tasks (job_task (jobs j))) ->
    sporadic_jobset_deadline_upto T tasks jobs H j ->
    job_index (jobs j) <
    S ((H - task_relative_deadline (tasks (job_task (jobs j))))
       / task_period (tasks (job_task (jobs j)))).
Proof.
  intros T tasks jobs H j Hwf Hd Hjobset.
  pose proof (sporadic_jobset_deadline_upto_implies_task_in_scope
                T tasks jobs H j Hjobset) as HT.
  pose proof (Hwf _ HT) as Hp.
  pose proof (sporadic_jobset_deadline_upto_implies_generated
                T tasks jobs H j Hjobset) as Hgen.
  pose proof (sporadic_jobset_deadline_upto_implies_deadline_le
                T tasks jobs H j Hjobset) as Hdl_le.
  pose proof (generated_sporadic_implies_valid_job_of_task tasks jobs j Hgen) as [Hdl_eq _].
  pose proof (generated_sporadic_implies_release_lb tasks jobs j Hgen) as Hreleq.
  unfold earliest_sporadic_release in Hreleq.
  (* Hreleq : job_index j * period ≤ job_release j                        *)
  (* Hdl_eq : abs_deadline = job_release j + rel_dl                        *)
  (* Hdl_le : abs_deadline ≤ H                                             *)
  (* So: job_index j * period ≤ H - rel_dl (needs nia for product)        *)
  apply Nat.lt_succ_r.
  apply (Nat.div_le_lower_bound
           (H - task_relative_deadline (tasks (job_task (jobs j))))
           (task_period (tasks (job_task (jobs j))))
           (job_index (jobs j))).
  + lia.
  + nia.
Qed.

(* ===== Count bound ===== *)

Lemma sporadic_jobs_of_task_deadline_upto_count_sound :
  forall T tasks jobs H τ l,
    well_formed_periodic_tasks_on T tasks ->
    0 < task_relative_deadline (tasks τ) ->
    NoDup l ->
    unique_task_index_on (sporadic_jobset_deadline_upto T tasks jobs H) jobs ->
    (forall j,
      In j l ->
      sporadic_jobset_deadline_upto T tasks jobs H j /\
      job_task (jobs j) = τ) ->
    length l <= S ((H - task_relative_deadline (tasks τ))
                   / task_period (tasks τ)).
Proof.
  intros T tasks jobs H τ l Hwf Hd Hnodup Huniq Hjobs.
  set (cnt := S ((H - task_relative_deadline (tasks τ))
                 / task_period (tasks τ))).
  pose (idx := fun j => job_index (jobs j)).
  assert (Hnodup_idx : NoDup (map idx l)).
  {
    eapply nodup_job_indices_of_unique_task_index; eauto.
  }
  assert (Hincl : incl (map idx l) (seq 0 cnt)).
  {
    intros k Hk.
    apply in_map_iff in Hk.
    destruct Hk as [j [Hidx Hj]].
    subst k.
    rewrite in_seq.
    split.
    - apply Nat.le_0_l.
    - destruct (Hjobs j Hj) as [Hjobset Htask].
      pose proof (sporadic_jobset_deadline_upto_implies_index_lt_dbf_count
                    T tasks jobs H j Hwf) as Hlt.
      rewrite Htask in Hlt.
      apply Hlt.
      + exact Hd.
      + exact Hjobset.
  }
  eapply Nat.le_trans.
  - replace (length l) with (length (map idx l)) by apply List.length_map.
    apply NoDup_incl_length with (l := map idx l) (l' := seq 0 cnt);
      try exact Hnodup_idx.
    exact Hincl.
  - rewrite length_seq. lia.
Qed.

(* ===== Demand bound ===== *)

(* The total demand of sporadic jobs with absolute deadline ≤ H is bounded by
   sporadic_dbf_bound (= periodic_dbf).  This is the sporadic analogue of
   periodic_demand_le_dbf. *)
Lemma sporadic_demand_le_dbf :
  forall T tasks jobs H τ l,
    well_formed_periodic_tasks_on T tasks ->
    0 < task_relative_deadline (tasks τ) ->
    NoDup l ->
    unique_task_index_on (sporadic_jobset_deadline_upto T tasks jobs H) jobs ->
    (forall j,
      In j l ->
      sporadic_jobset_deadline_upto T tasks jobs H j /\
      job_task (jobs j) = τ) ->
    total_job_cost jobs l <= sporadic_dbf_bound tasks τ H.
Proof.
  intros T tasks jobs H τ l Hwf Hd Hnodup Huniq Hjobs.
  unfold sporadic_dbf_bound, periodic_dbf.
  destruct (Nat.ltb_spec H (task_relative_deadline (tasks τ))) as [Hlt | Hge].
  - (* H < d: DBF = 0, so l must be empty *)
    assert (Hl : l = []).
    {
      destruct l as [| j l']; [reflexivity |].
      exfalso.
      destruct (Hjobs j (in_eq j l')) as [Hjobset Htask].
      pose proof (sporadic_jobset_deadline_upto_implies_generated
                    T tasks jobs H j Hjobset) as Hgen.
      pose proof (sporadic_jobset_deadline_upto_implies_deadline_le
                    T tasks jobs H j Hjobset) as Hdl_le.
      pose proof (generated_sporadic_implies_valid_job_of_task tasks jobs j Hgen) as Hvalid.
      pose proof (generated_sporadic_implies_release_lb tasks jobs j Hgen) as Hreleq.
      unfold earliest_sporadic_release in Hreleq.
      destruct Hvalid as [Hdl_eq _].
      rewrite Htask in Hdl_eq.
      lia.
    }
    subst l. simpl. lia.
  - (* H ≥ d: use count bound *)
    eapply Nat.le_trans.
    + eapply (total_job_cost_le_length_mul jobs l (task_cost (tasks τ))).
      intros j Hj.
      destruct (Hjobs j Hj) as [Hjobset Htask].
      rewrite <- Htask.
      exact (proj2 (sporadic_jobset_deadline_upto_implies_valid
                      T tasks jobs H j Hjobset)).
    + pose proof (sporadic_jobs_of_task_deadline_upto_count_sound
                    T tasks jobs H τ l Hwf Hd Hnodup Huniq Hjobs) as Hcount.
      apply Nat.mul_le_mono_r.
      exact Hcount.
Qed.
