From Stdlib Require Import Arith Arith.PeanoNat Lia List.
From RocqSched Require Import Foundation.Base.
From RocqSched Require Import TaskModels.Periodic.PeriodicTasks.
From RocqSched Require Import TaskModels.Periodic.PeriodicFiniteHorizon.
From RocqSched Require Import TaskModels.Periodic.PeriodicWorkload.
From RocqSched Require Import TaskModels.Sporadic.SporadicTasks.
From RocqSched Require Import TaskModels.Sporadic.SporadicFiniteHorizon.
From RocqSched Require Import TaskModels.Sporadic.SporadicWorkload.
From RocqSched Require Import TaskModels.Jitter.JitteredPeriodicTasks.
From RocqSched Require Import TaskModels.Jitter.JitteredPeriodicFiniteHorizon.
From RocqSched Require Import TaskModels.Jitter.JitteredPeriodicWorkload.
From RocqSched Require Import Analysis.Common.WorkloadAggregation.
From RocqSched Require Import Analysis.Uniprocessor.RequestBound.

Import ListNotations.

(**
  Examples/RequestBoundExamples.v
  ================================
  Concrete examples illustrating the Request-Bound Function (RBF) API.

  We verify:
  1. Concrete periodic_rbf values for a simple task set.
  2. Monotonicity in action.
  3. sporadic_rbf_bound equals periodic_rbf (definitionally).
  4. periodic_rbf ≤ old coarse bound (H * wcet).
  5. workload_le_rbf bridge in use.
*)

(* ===== Example 1: concrete periodic_rbf values ===== *)

(* Task: period = 5, wcet = 2 *)
Definition example_task : Task := {|
  task_cost     := 2;
  task_period   := 5;
  task_relative_deadline := 5
|}.

Definition example_tasks : TaskId -> Task := fun _ => example_task.

(* periodic_rbf example_tasks 0 10 = ⌈10/5⌉ × 2 = 2 × 2 = 4 *)
Example periodic_rbf_ex1 :
  periodic_rbf example_tasks 0 10 = 4.
Proof. reflexivity. Qed.

(* periodic_rbf example_tasks 0 11 = ⌈11/5⌉ × 2 = 3 × 2 = 6 *)
Example periodic_rbf_ex2 :
  periodic_rbf example_tasks 0 11 = 6.
Proof. reflexivity. Qed.

(* periodic_rbf example_tasks 0 0 = 0 *)
Example periodic_rbf_ex3 :
  periodic_rbf example_tasks 0 0 = 0.
Proof. apply periodic_rbf_zero. Qed.

(* ===== Example 2: monotonicity ===== *)

(* The RBF is non-decreasing: rbf(10) ≤ rbf(15) *)
Example periodic_rbf_monotone_ex :
  periodic_rbf example_tasks 0 10 <= periodic_rbf example_tasks 0 15.
Proof.
  apply periodic_rbf_monotone. lia.
Qed.

(* ===== Example 3: sporadic_rbf_bound = periodic_rbf ===== *)

Example sporadic_eq_periodic_ex :
  sporadic_rbf_bound example_tasks 0 10 = periodic_rbf example_tasks 0 10.
Proof. apply sporadic_rbf_bound_eq_periodic_rbf. Qed.

(* ===== Example 4: periodic_rbf ≤ old coarse bound (H × wcet) ===== *)

(* For the example task with period 5, rbf(H) ≤ H × 2 *)
Example periodic_rbf_le_coarse_ex :
  forall H, periodic_rbf example_tasks 0 H <= H * 2.
Proof.
  intro H.
  apply periodic_rbf_le_coarse_bound.
  unfold example_tasks, example_task. simpl. lia.
Qed.

(* ===== Example 5: workload_le_rbf bridge ===== *)

(* Set up a concrete scenario: one periodic task, one job. *)

(* A single job for task 0, released at time 2, with cost 2. *)
Definition ex_job : Job := {|
  job_task         := 0;
  job_index        := 0;
  job_release      := 0;
  job_cost         := 2;
  job_abs_deadline := 5
|}.

Definition ex_jobs : JobId -> Job := fun _ => ex_job.

(* All tasks have period 5. *)
Definition ex_tasks : TaskId -> Task := example_tasks.

(* Offset is 0. *)
Definition ex_offset : TaskId -> Time := fun _ => 0.

(* The single job is generated by the periodic task model. *)
Lemma ex_job_generated :
  generated_by_periodic_task ex_tasks ex_offset ex_jobs 0.
Proof.
  unfold generated_by_periodic_task, ex_jobs, ex_job,
         ex_tasks, example_tasks, example_task, ex_offset.
  simpl.
  repeat split; lia.
Qed.

(* The single job is in the horizon-10 jobset. *)
Lemma ex_job_in_jobset :
  periodic_jobset_upto (fun _ => True) ex_tasks ex_offset ex_jobs 10 0.
Proof.
  unfold periodic_jobset_upto, ex_jobs, ex_job,
         ex_tasks, example_tasks, example_task, ex_offset.
  simpl.
  repeat split.
  - apply ex_job_generated.
  - lia.
Qed.

(* The workload of the singleton job list is bounded by periodic_rbf. *)
Example workload_le_rbf_ex :
  total_job_cost ex_jobs [0] <= periodic_rbf ex_tasks 0 10.
Proof.
  apply (periodic_workload_le_rbf
           (fun _ => True) ex_tasks ex_offset ex_jobs 10 0 [0]).
  - (* well_formed *)
    intros τ _.
    unfold ex_tasks, example_tasks, example_task. simpl. lia.
  - (* NoDup on indices *)
    constructor.
    + simpl. tauto.
    + constructor.
  - (* All jobs satisfy the jobset predicate *)
    intros j Hj.
    simpl in Hj.
    destruct Hj as [Hj | []].
    subst j.
    split.
    + apply ex_job_in_jobset.
    + reflexivity.
Qed.

(* ===== Example 6: jittered-periodic falls into sporadic bound ===== *)

(* jittered_periodic_workload_upto_le_sporadic_bound says that any
   jittered-periodic workload is bounded by sporadic_workload_upto_bound,
   which equals sporadic_rbf_bound = periodic_rbf. *)
Example jittered_le_sporadic_rbf :
  forall T tasks offset jitter jobs H τ l,
    well_formed_periodic_tasks_on T tasks ->
    NoDup l ->
    unique_task_index_on
      (jittered_periodic_jobset_upto T tasks offset jitter jobs H) jobs ->
    sporadic_separation_on
      (jittered_periodic_jobset_upto T tasks offset jitter jobs H) tasks jobs ->
    (forall j, In j l ->
      jittered_periodic_jobset_upto T tasks offset jitter jobs H j /\
      job_task (jobs j) = τ) ->
    total_job_cost jobs l <= sporadic_rbf_bound tasks τ H.
Proof.
  intros T tasks offset jitter jobs H τ l Hwf Hnodup Huniq Hsep Hjobs.
  rewrite <- sporadic_workload_upto_bound_eq_rbf.
  exact (jittered_periodic_workload_upto_le_sporadic_bound
           T tasks offset jitter jobs H τ l
           Hwf Hnodup Huniq Hsep Hjobs).
Qed.
