From Stdlib Require Import Arith Arith.PeanoNat Lia List.
From RocqSched Require Import Foundation.Base.
From RocqSched Require Import TaskModels.Periodic.PeriodicTasks.
From RocqSched Require Import TaskModels.Sporadic.SporadicTasks.
From RocqSched Require Import TaskModels.Sporadic.SporadicWorkload.
From RocqSched Require Import TaskModels.Jitter.JitteredPeriodicTasks.
From RocqSched Require Import TaskModels.Jitter.JitteredPeriodicFiniteHorizon.
From RocqSched Require Import TaskModels.Jitter.JitteredPeriodicSporadicBridge.
From RocqSched Require Import TaskModels.Sporadic.SporadicDemandBound.
From RocqSched Require Import Analysis.Common.WorkloadAggregation.
From RocqSched Require Import Analysis.Uniprocessor.DemandBound.
From RocqSched Require Import Analysis.Uniprocessor.ProcessorDemand.

Import ListNotations.

(* ===== Deadline-Bounded Finite Horizon for Jittered-Periodic Tasks ===== *)

(* The deadline-bounded jobset for jittered-periodic tasks:
   jobs whose task is in scope, generated by the jittered-periodic model,
   and whose absolute deadline is at most H.

   Because jittered-periodic generation implies sporadic generation
   (generated_by_jittered_periodic_implies_sporadic), the demand bound
   reduces to the sporadic case: total demand ≤ sporadic_dbf_bound = periodic_dbf. *)
Definition jittered_periodic_jobset_deadline_upto
    (T : TaskId -> Prop)
    (tasks : TaskId -> Task)
    (offset : TaskId -> Time)
    (jitter : TaskId -> Time)
    (jobs : JobId -> Job)
    (H : Time) : JobId -> Prop :=
  fun j =>
    T (job_task (jobs j)) /\
    generated_by_jittered_periodic_task tasks offset jitter jobs j /\
    job_abs_deadline (jobs j) <= H.

(* ===== Basic extraction lemmas ===== *)

Lemma jittered_periodic_jobset_deadline_upto_implies_task_in_scope :
  forall T tasks offset jitter jobs H j,
    jittered_periodic_jobset_deadline_upto T tasks offset jitter jobs H j ->
    T (job_task (jobs j)).
Proof.
  intros T tasks offset jitter jobs H j [HT _]. exact HT.
Qed.

Lemma jittered_periodic_jobset_deadline_upto_implies_generated :
  forall T tasks offset jitter jobs H j,
    jittered_periodic_jobset_deadline_upto T tasks offset jitter jobs H j ->
    generated_by_jittered_periodic_task tasks offset jitter jobs j.
Proof.
  intros T tasks offset jitter jobs H j [_ [Hgen _]]. exact Hgen.
Qed.

Lemma jittered_periodic_jobset_deadline_upto_implies_deadline_le :
  forall T tasks offset jitter jobs H j,
    jittered_periodic_jobset_deadline_upto T tasks offset jitter jobs H j ->
    job_abs_deadline (jobs j) <= H.
Proof.
  intros T tasks offset jitter jobs H j [_ [_ Hdl]]. exact Hdl.
Qed.

(* ===== Bridge to sporadic jobset ===== *)

(* Every jittered-periodic job with deadline ≤ H is also a sporadic job
   with deadline ≤ H.  This follows from
   generated_by_jittered_periodic_implies_sporadic. *)
Lemma jittered_periodic_jobset_deadline_upto_implies_sporadic :
  forall T tasks offset jitter jobs H j,
    jittered_periodic_jobset_deadline_upto T tasks offset jitter jobs H j ->
    sporadic_jobset_deadline_upto T tasks jobs H j.
Proof.
  intros T tasks offset jitter jobs H j [HT [Hgen Hdl]].
  split.
  - exact HT.
  - split.
    + exact (generated_by_jittered_periodic_implies_sporadic tasks offset jitter jobs j Hgen).
    + exact Hdl.
Qed.

(* ===== Demand bound ===== *)

(* The total demand of jittered-periodic jobs with absolute deadline ≤ H is
   bounded by jittered_periodic_dbf_bound (= periodic_dbf), via the sporadic
   bridge above.  We lift sporadic_demand_le_dbf directly. *)
Lemma jittered_periodic_demand_le_dbf :
  forall T tasks offset jitter jobs H τ l,
    well_formed_periodic_tasks_on T tasks ->
    0 < task_relative_deadline (tasks τ) ->
    NoDup l ->
    unique_task_index_on (sporadic_jobset_deadline_upto T tasks jobs H) jobs ->
    (forall j,
      In j l ->
      jittered_periodic_jobset_deadline_upto T tasks offset jitter jobs H j /\
      job_task (jobs j) = τ) ->
    total_job_cost jobs l <= jittered_periodic_dbf_bound tasks τ H.
Proof.
  intros T tasks offset jitter jobs H τ l Hwf Hd Hnodup Huniq Hjobs.
  unfold jittered_periodic_dbf_bound, sporadic_dbf_bound.
  apply (sporadic_demand_le_dbf T tasks jobs H τ l Hwf Hd Hnodup Huniq).
  intros j Hj.
  destruct (Hjobs j Hj) as [Hjobset Htask].
  split.
  - exact (jittered_periodic_jobset_deadline_upto_implies_sporadic
             T tasks offset jitter jobs H j Hjobset).
  - exact Htask.
Qed.

Lemma jittered_periodic_total_demand_le_taskset_dbf :
  forall T tasks offset jitter jobs H enumT l,
    well_formed_periodic_tasks_on T tasks ->
    (forall τ, In τ enumT -> 0 < task_relative_deadline (tasks τ)) ->
    NoDup enumT ->
    NoDup l ->
    unique_task_index_on (sporadic_jobset_deadline_upto T tasks jobs H) jobs ->
    (forall j,
      In j l ->
      jittered_periodic_jobset_deadline_upto T tasks offset jitter jobs H j /\
      In (job_task (jobs j)) enumT) ->
    total_job_cost jobs l <= taskset_jittered_periodic_dbf_bound tasks enumT H.
Proof.
  intros T tasks offset jitter jobs H enumT l Hwf Hdl HnodupT HnodupL Huniq Hjobs.
  unfold taskset_jittered_periodic_dbf_bound, taskset_sporadic_dbf_bound.
  eapply sporadic_total_demand_le_taskset_dbf.
  - exact Hwf.
  - exact Hdl.
  - exact HnodupT.
  - exact HnodupL.
  - exact Huniq.
  - intros j Hj.
    destruct (Hjobs j Hj) as [Hjobset Hin].
    split.
    + exact (jittered_periodic_jobset_deadline_upto_implies_sporadic
               T tasks offset jitter jobs H j Hjobset).
    + exact Hin.
Qed.
